version: "1.0"
services:
  django-server1:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Almaty
    depends_on:
      - postgresql
      - redis

  django-server2:
    build: .
    ports:
      - "8001:8000"
    environment:
      - TZ=Asia/Almaty
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/app/var/static
    depends_on:
      - django-server1
      - django-server2

volumes:
  postgresql-data: