version: "1.0"
services:
  django-server:
    build: .
    environment:
      - TZ=Asia/Almaty
    depends_on:
      - postgresql
      - redis
    volumes:
      - static-volume:/app/static

  postgresql:
    container_name: postgresql
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: blog
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
      - static-volume:/app/var/static
    depends_on:
      - django-server

volumes:
  postgresql-data:
  static-volume: