# Generated by Django 5.1.1 on 2024-09-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_created_37c50a_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at', 'author_id'], name='blog_post_created_37c50a_idx'),
        ),
    ]
